//
//  JpnJISColors.swift
//  HKLColorTable
//
//  Created by Hirohito Kato on 2016/04/16.
//  Copyright © 2016 Hirohito Kato. All rights reserved.
//

import UIKit

/// JIS Japanese traditional color name : http://2xup.org/repos/
public enum JpnColor: Int {
    case SakuraIro = 0      // 和色名 桜色 / 0xfef4f4
    case AzukiIro           // 和色名 小豆色 / 0x96514d
    case Kogane             // 和色名 黄金 / 0xe6b422
    case MoegiIro           // 和色名 萌葱色 / 0x006e54
    case Kodaimurasaki      // 和色名 古代紫 / 0x895b8a
    case Usuzakura          // 和色名 薄桜 / 0xfdeff2
    case Karacha            // 和色名 枯茶 / 0x8d6449
    case Hajizome           // 和色名 櫨染 / 0xd9a62e
    case Hanarokushou       // 和色名 花緑青 / 0x00a381
    case Nasukon            // 和色名 茄子紺 / 0x824880
    case Sakuranezu         // 和色名 桜鼠 / 0xe9dfe5
    case AmeIro             // 和色名 飴色 / 0xdeb068
    case KikuchibaIro       // 和色名 黄朽葉色 / 0xd3a243
    case HisuiIro           // 和色名 翡翠色 / 0x38b48b
    case Futaai             // 和色名 二藍 / 0x915c8b
    case Tokinezu           // 和色名 鴇鼠 / 0xe4d2d8
    case RakudaIro          // 和色名 駱駝色 / 0xbf794e
    case Yamabukicha        // 和色名 山吹茶 / 0xc89932
    case Aomidori           // 和色名 青緑 / 0x00a497
    case Kyoumurasaki       // 和色名 京紫 / 0x9d5b8b
    case NijiIro            // 和色名 虹色 / 0xf6bfbc
    case TsuchiIro          // 和色名 土色 / 0xbc763c
    case KarashiIro         // 和色名 芥子色 / 0xd0af4c
    case Mizuasagi          // 和色名 水浅葱 / 0x80aba9
    case Ebizome            // 和色名 蒲葡 / 0x7a4171
    case SangoIro           // 和色名 珊瑚色 / 0xf5b1aa
    case Kigaracha          // 和色名 黄唐茶 / 0xb98c46
    case Mamegaracha        // 和色名 豆がら茶 / 0x8b968d
    case Sabiasagi          // 和色名 錆浅葱 / 0x5c9291
    case Wakamurasaki       // 和色名 若紫 / 0xbc64a4
    case Ikkonzome          // 和色名 一斤染 / 0xf5b199
    case Kuwazome           // 和色名 桑染 / 0xb79b5b
    case Kikujin            // 和色名 麹塵 / 0x6e7955
    case Seiheki            // 和色名 青碧 / 0x478384
    case Benimurasaki       // 和色名 紅紫 / 0xb44c97
    case ShishiIro          // 和色名 宍色 / 0xefab93
    case HajiIro            // 和色名 櫨色 / 0xb77b57
    case YamabatoIro        // 和色名 山鳩色 / 0x767c6b
    case Omeshicha          // 和色名 御召茶 / 0x43676b
    case Umemurasaki        // 和色名 梅紫 / 0xaa4c8f
    case KoubaiIro          // 和色名 紅梅色 / 0xf2a0a1
    case Kitsurubami        // 和色名 黄橡 / 0xb68d4c
    case Rikyuunezumi       // 和色名 利休鼠 / 0x888e7e
    case Minatonezumi       // 和色名 湊鼠 / 0x80989b
    case AyameIro           // 和色名  菖蒲色 / 0xcc7eb1
    case Usubeni            // 和色名 薄紅 / 0xf0908d
    case Tyoujizome         // 和色名 丁字染 / 0xad7d4c
    case Mirucha            // 和色名 海松茶 / 0x5a544b
    case Kourainando        // 和色名 高麗納戸 / 0x2c4f54
    case BenifujiIro        // 和色名 紅藤色 / 0xcca6bf
    case Jinzamomi          // 和色名 甚三紅 / 0xee827c
    case Kouzome            // 和色名 香染 / 0xad7d4c
    case Aimirucha          // 和色名 藍海松茶 / 0x56564b
    case Momoshiocha        // 和色名 百入茶 / 0x1f3134
    case Asamurasaki        // 和色名 浅紫 / 0xc4a3bf
    case MomoIro            // 和色名 桃色 / 0xf09199
    case Biwacha            // 和色名 枇杷茶 / 0xae7c4f
    case Aikobicha          // 和色名 藍媚茶 / 0x555647
    case Sabinezu           // 和色名 錆鼠 / 0x47585c
    case Murasakisuishou    // 和色名 紫水晶 / 0xe7e7eb
    case TokiIro            // 和色名 鴇色 / 0xf4b3c2
    case Shikancha          // 和色名 芝翫茶 / 0xad7e4e
    case Sensaicha          // 和色名 千歳茶 / 0x494a41
    case Sabitetsuonando    // 和色名 錆鉄御納戸 / 0x485859
    case Usuumenezu         // 和色名 薄梅鼠 / 0xdcd6d9
    case NadeshikoIro       // 和色名 撫子色 / 0xeebbcb
    case Kogarekou          // 和色名 焦香 / 0xae7c58
    case Iwaicha            // 和色名 岩井茶 / 0x6b6f59
    case Ainezu             // 和色名 藍鼠 / 0x6c848d
    case Akatsukinezu       // 和色名 暁鼠 / 0xd3cfd9
    case Haiume             // 和色名 灰梅 / 0xe8d3c7
    case KurumiIro          // 和色名 胡桃色 / 0xa86f4c
    case Sensaicha2         // 和色名 仙斎茶 / 0x474b42
    case Sabionando         // 和色名 錆御納戸 / 0x53727d
    case Botannezu          // 和色名 牡丹鼠 / 0xd3ccd6
    case Haizakura          // 和色名 灰桜 / 0xe8d3d1
    case ShibukamiIro       // 和色名 渋紙色 / 0x946243
    case Kuromidori         // 和色名 黒緑 / 0x333631
    case MasuhanaIro        // 和色名 舛花色 / 0x5b7e91
    case KasumiIro          // 和色名 霞色 / 0xc8c2c6
    case Awabenifuji        // 和色名 淡紅藤 / 0xe6cde3
    case KuchibaIro         // 和色名 朽葉色 / 0x917347
    case Yanagisusutake     // 和色名 柳煤竹 / 0x5b6356
    case NoshimehanaIro     // 和色名 熨斗目花色 / 0x426579
    case Fujinezu           // 和色名 藤鼠 / 0xa6a5c4
    case SekichikuIro       // 和色名 石竹色 / 0xe5abbe
    case Kuwacha            // 和色名 桑茶 / 0x956f29
    case KabachaIro         // 和色名 樺茶色 / 0x726250
    case Omeshionando       // 和色名 御召御納戸 / 0x4c6473
    case HashitaIro         // 和色名 半色 / 0xa69abd
    case Usukoubai          // 和色名 薄紅梅 / 0xe597b2
    case Rokoucha           // 和色名 路考茶 / 0x8c7042
    case UtsubushiIro       // 和色名 空五倍子色 / 0x9d896c
    case Tetsuonando        // 和色名 鉄御納戸 / 0x455765
    case UsuIro             // 和色名 薄色 / 0xa89dac
    case MomohanaIro        // 和色名 桃花色 / 0xe198b4
    case KokubouShoku       // 和色名 国防色 / 0x7b6c3e
    case NamakabeIro        // 和色名 生壁色 / 0x94846a
    case Konnezu            // 和色名 紺鼠 / 0x44617b
    case Usunezu            // 和色名 薄鼠 / 0x9790a4
    case Mizugaki           // 和色名 水柿 / 0xe4ab9b
    case KyaraIro           // 和色名 伽羅色 / 0xd8a373
    case Higosusutake       // 和色名 肥後煤竹 / 0x897858
    case Aitetsu            // 和色名 藍鉄 / 0x393f4c
    case Hatobanezumi       // 和色名 鳩羽鼠 / 0x9e8b8e
    case Tokigaracha        // 和色名 ときがら茶 / 0xe09e87
    case Edocha             // 和色名 江戸茶 / 0xcd8c5c
    case Kobicha            // 和色名 媚茶 / 0x716246
    case Aokachi            // 和色名 青褐 / 0x393e4f
    case HatobaIro          // 和色名 鳩羽色 / 0x95859c
    case Arazome            // 和色名 退紅 / 0xd69090
    case KabaIro            // 和色名 樺色 / 0xcd5e3c
    case Shirotsurubami     // 和色名 白橡 / 0xcbb994
    case Kachikaeshi        // 和色名 褐返 / 0x203744
    case Kikyounezu         // 和色名 桔梗鼠 / 0x95949a
    case Usugaki            // 和色名 薄柿 / 0xd4acad
    case Beniukon           // 和色名 紅鬱金 / 0xcb8347
    case AmaIro             // 和色名 亜麻色 / 0xd6c6af
    case KachiIro           // 和色名 褐色 / 0x4d4c61
    case Murasakinezu       // 和色名 紫鼠 / 0x71686c
    case TyoushunIro        // 和色名 長春色 / 0xc97586
    case KawarakeIro        // 和色名 土器色 / 0xc37854
    case HashibamiIro       // 和色名 榛色 / 0xbfa46f
    case Geppaku            // 和色名 月白 / 0xeaf4fc
    case Budounezumi        // 和色名 葡萄鼠 / 0x705b67
    case Umenezu            // 和色名 梅鼠 / 0xc099a0
    case KitsuneIro         // 和色名 狐色 / 0xc38743
    case AkuIro             // 和色名 灰汁色 / 0x9e9478
    case ShirosumireIro     // 和色名 白菫色 / 0xeaedf7
    case KokiIro            // 和色名 濃色 / 0x634950
    case Tokiasagi          // 和色名 鴇浅葱 / 0xb88884
    case OudoIro            // 和色名 黄土色 / 0xc39143
    case Rikyuucha          // 和色名 利休茶 / 0xa59564
    case ShirahanaIro       // 和色名 白花色 / 0xe8ecef
    case Murasakitobi       // 和色名 紫鳶 / 0x5f414b
    case Umezome            // 和色名 梅染 / 0xb48a76
    case KohakuIro          // 和色名 琥珀色 / 0xbf783a
    case Uguisucha          // 和色名 鶯茶 / 0x715c1f
    case Aijiro             // 和色名 藍白 / 0xebf6f7
    case Koinezu            // 和色名 濃鼠 / 0x4f455c
    case Suoukou            // 和色名 蘇芳香 / 0xa86965
    case Akacha             // 和色名 赤茶 / 0xbb5535
    case Mokuranjiki        // 和色名 木蘭色 / 0xc7b370
    case Shiraai            // 和色名 白藍 / 0xc1e4e9
    case Fujisusutake       // 和色名 藤煤竹 / 0x5a5359
    case Asasuou            // 和色名 浅蘇芳 / 0xa25768
    case Taisha             // 和色名 代赭 / 0xbb5520
    case SunaIro            // 和色名 砂色 / 0xdcd3b2
    case MizuIro            // 和色名 水色 / 0xbce2e8
    case Keshimurasaki      // 和色名 滅紫 / 0x594255
    case Masoo              // 和色名 真朱 / 0xec6d71
    case RengaIro           // 和色名 煉瓦色 / 0xb55233
    case AburaIro           // 和色名 油色 / 0xa19361
    case Kamenozoki         // 和色名 瓶覗 / 0xa2d7dd
    case Benikeshinezumi    // 和色名 紅消鼠 / 0x524748
    case Akamurasaki        // 和色名 赤紫 / 0xeb6ea5
    case Suzumecha          // 和色名 雀茶 / 0xaa4f37
    case RikyuuIro          // 和色名 利休色 / 0x8f8667
    case HisokuIro          // 和色名 秘色色 / 0xabced8
    case Nisemurasaki       // 和色名 似せ紫 / 0x513743
    case TsutsujiIro        // 和色名 躑躅色 / 0xe95295
    case Danjuuroucha       // 和色名 団十郎茶 / 0x9f563a
    case Baikoucha          // 和色名 梅幸茶 / 0x887938
    case SoraIro            // 和色名 空色 / 0xa0d8ef
    case Haikimidori        // 和色名 灰黄緑 / 0xe6eae3
    case BotanIro           // 和色名 牡丹色 / 0xe7609e
    case KakishibuIro       // 和色名 柿渋色 / 0x9f563a
    case Rikancha           // 和色名 璃寛茶 / 0x6a5d21
    case WasurenagusaIro    // 和色名 勿忘草色 / 0x89c3eb
    case SobakiriIro        // 和色名 蕎麦切色 / 0xd4dcd6
    case ImayouIro          // 和色名 今様色 / 0xd0576b
    case Benitobi           // 和色名 紅鳶 / 0x9a493f
    case Kimirucha          // 和色名 黄海松茶 / 0x918754
    case AofujiIro          // 和色名 青藤色 / 0x84a2d4
    case Usukumonezu        // 和色名 薄雲鼠 / 0xd4dcda
    case Nakabeni           // 和色名 中紅 / 0xc85179
    case Haicha             // 和色名 灰茶 / 0x98623c
    case NataneyuIro        // 和色名 菜種油色 / 0xa69425
    case Byakugun           // 和色名 白群 / 0x83ccd2
    case KarenoIro          // 和色名 枯野色 / 0xd3cbc6
    case BaraIro            // 和色名 薔薇色 / 0xe9546b
    case ChaIro             // 和色名 茶色 / 0x965042
    case Aokuchiba          // 和色名 青朽葉 / 0xada250
    case Asahanada          // 和色名 浅縹 / 0x84b9cb
    case UrumiIro           // 和色名 潤色 / 0xc8c2be
    case Karakurenai        // 和色名 韓紅 / 0xe95464
    case HiwadaIro          // 和色名 檜皮色 / 0x965036
    case NegishiIro         // 和色名 根岸色 / 0x938b4b
    case UsuhanaIro         // 和色名 薄花色 / 0x698aab
    case Rikyuushirocha     // 和色名 利休白茶 / 0xb3ada0
    case Ginshu             // 和色名 銀朱 / 0xc85554
    case TobiIro            // 和色名 鳶色 / 0x95483f
    case Hiwacha            // 和色名 鶸茶 / 0x8c8861
    case NandoIro           // 和色名 納戸色 / 0x008899
    case Chanezumi          // 和色名 茶鼠 / 0xa99e93
    case Akabeni            // 和色名 赤紅 / 0xc53d43
    case Kakicha            // 和色名 柿茶 / 0x954e2a
    case Yanagicha          // 和色名 柳茶 / 0xa1a46d
    case AsagiIro           // 和色名 浅葱色 / 0x00a3af
    case Kurumizome         // 和色名 胡桃染 / 0xa58f86
    case Benihi             // 和色名 紅緋 / 0xe83929
    case BengaraIro         // 和色名 弁柄色 / 0x8f2e14
    case MiruIro            // 和色名 海松色 / 0x726d40
    case Hanaasagi          // 和色名 花浅葱 / 0x2a83a2
    case Edonezu            // 和色名 江戸鼠 / 0x928178
    case Aka                // 和色名 赤 / 0xe60033
    case AkasabiIro         // 和色名 赤錆色 / 0x8a3319
    case UguisuIro          // 和色名 鶯色 / 0x928c36
    case ShinbashiIro       // 和色名 新橋色 / 0x59b9c6
    case SusuIro            // 和色名 煤色 / 0x887f7a
    case Shoujouhi          // 和色名 猩々緋 / 0xe2041b
    case Kasshoku           // 和色名 褐色 / 0x8a3b00
    case RyokuouShoku       // 和色名 緑黄色 / 0xdccb18
    case AmaIro2            // 和色名 天色 / 0x2ca9e1
    case Tyoujicha          // 和色名 丁子茶 / 0xb4866b
    case Kurenai            // 和色名 紅 / 0xd7003a
    case Kuriume            // 和色名 栗梅 / 0x852e19
    case HiwaIro            // 和色名 鶸色 / 0xd7cf3a
    case TsuyukusaIro       // 和色名 露草色 / 0x38a1db
    case Fushizome          // 和色名 柴染 / 0xb28c6e
    case Kokihi             // 和色名 深緋 / 0xc9171e
    case Benihihada         // 和色名 紅檜皮 / 0x7b4741
    case MacchaIro          // 和色名 抹茶色 / 0xc5c56a
    case Ao                 // 和色名 青 / 0x0095d9
    case Soudenkaracha      // 和色名 宗伝唐茶 / 0xa16d5d
    case HiIro              // 和色名 緋色 / 0xd3381c
    case Ebicha             // 和色名 海老茶 / 0x773c30
    case WakakusaIro        // 和色名 若草色 / 0xc3d825
    case Usuai              // 和色名 薄藍 / 0x0094c8
    case Tonocha            // 和色名 砺茶 / 0x9f6f55
    case Akani              // 和色名 赤丹 / 0xce5242
    case Karacha2           // 和色名 唐茶 / 0x783c1d
    case Kimidori           // 和色名 黄緑 / 0xb8d200
    case HanadaIro          // 和色名 縹色 / 0x2792c3
    case SenchaIro          // 和色名 煎茶色 / 0x8c6450
    case Beniaka            // 和色名 紅赤 / 0xd9333f
    case KuriIro            // 和色名 栗色 / 0x762f07
    case WakameIro          // 和色名 若芽色 / 0xe0ebaf
    case Konpeki            // 和色名 紺碧 / 0x007bbb
    case Ginsusudake        // 和色名 銀煤竹 / 0x856859
    case Enji               // 和色名 臙脂 / 0xb94047
    case ShakudouIro        // 和色名 赤銅色 / 0x752100
    case WakanaIro          // 和色名 若菜色 / 0xd8e698
    case Usugunjou          // 和色名 薄群青 / 0x5383c3
    case Kigaracha2         // 和色名 黄枯茶 / 0x765c47
    case Ake                // 和色名 朱・緋 / 0xba2636
    case SabiIro            // 和色名 錆色 / 0x6c3524
    case WakanaeIro         // 和色名 若苗色 / 0xc7dc68
    case Usuhanazakura      // 和色名 薄花桜 / 0x5a79ba
    case SusutakeIro        // 和色名 煤竹色 / 0x6f514c
    case AkaneIro           // 和色名 茜色 / 0xb7282e
    case Sekkasshoku        // 和色名 赤褐色 / 0x683f36
    case Aoni               // 和色名 青丹 / 0x99ab4e
    case GunjouIro          // 和色名 群青色 / 0x4c6cb3
    case Kogecha            // 和色名 焦茶 / 0x6f4b3e
    case Beniebicha         // 和色名 紅海老茶 / 0xa73836
    case Chakasshoku        // 和色名 茶褐色 / 0x664032
    case KusaIro            // 和色名 草色 / 0x7b8d42
    case KakitsubataIro     // 和色名 杜若色 / 0x3e62ad
    case Kurotsurubami      // 和色名 黒橡 / 0x544a47
    case Suou               // 和色名 蘇芳 / 0x9e3d3f
    case Kurikawacha        // 和色名 栗皮茶 / 0x6d3c32
    case KokeIro            // 和色名 苔色 / 0x69821b
    case RuriIro            // 和色名 瑠璃色 / 0x1e50a2
    case KenpouIro          // 和色名 憲法色 / 0x543f32
    case Shinku             // 和色名 真紅 / 0xa22041
    case Kurocha            // 和色名 黒茶 / 0x583822
    case Moegi              // 和色名 萌黄 / 0xaacf53
    case Usuhanada          // 和色名 薄縹 / 0x507ea4
    case KuriIro2           // 和色名 涅色 / 0x554738
    case Koikurenai         // 和色名 濃紅 / 0xa22041
    case Ebicha2            // 和色名 葡萄茶 / 0x6c2c2f
    case NaeIro             // 和色名 苗色 / 0xb0ca71
    case Rurikon            // 和色名 瑠璃紺 / 0x19448e
    case Binroujizome       // 和色名 檳榔子染 / 0x433d3c
    case ZougeIro           // 和色名 象牙色 / 0xf8f4e6
    case EbiIro             // 和色名 葡萄色 / 0x640125
    case WakabaIro          // 和色名 若葉色 / 0xb9d08b
    case Konruri            // 和色名 紺瑠璃 / 0x164a84
    case Kurotobi           // 和色名 黒鳶 / 0x432f2f
    case NeriIro            // 和色名 練色 / 0xede4cd
    case KanzouIro          // 和色名 萱草色 / 0xf8b862
    case MatsubaIro         // 和色名 松葉色 / 0x839b5c
    case AiIro              // 和色名 藍色 / 0x165e83
    case Akasumi            // 和色名 赤墨 / 0x3f312b
    case KaihakuShoku       // 和色名 灰白色 / 0xe9e4d4
    case KoujiIro           // 和色名 柑子色 / 0xf6ad49
    case NatsumushiIro      // 和色名 夏虫色 / 0xcee4ae
    case Seiran             // 和色名 青藍 / 0x274a78
    case Kurobeni           // 和色名 黒紅 / 0x302833
    case MushiguriIro       // 和色名 蒸栗色 / 0xebe1a9
    case Kincha             // 和色名 金茶 / 0xf39800
    case Hiwamoegi          // 和色名 鶸萌黄 / 0x82ae46
    case Kokihanada         // 和色名 深縹 / 0x2a4073
    case Shiro              // 和色名 白 / 0xffffff
    case Ominaeshi          // 和色名 女郎花 / 0xf2f2b0
    case MikanIro           // 和色名 蜜柑色 / 0xf08300
    case YanagiIro          // 和色名 柳色 / 0xa8c97f
    case KonIro             // 和色名 紺色 / 0x223a70
    case GofunIro           // 和色名 胡粉色 / 0xfffffc
    case KarekusaIro        // 和色名 枯草色 / 0xe4dc8a
    case EntanIro           // 和色名 鉛丹色 / 0xec6d51
    case Aoshirotsurubami   // 和色名 青白橡 / 0x9ba88d
    case Konjou             // 和色名 紺青 / 0x192f60
    case UnohanaIro         // 和色名 卯の花色 / 0xf7fcfe
    case Tankou             // 和色名 淡黄 / 0xf8e58c
    case Ouni               // 和色名 黄丹 / 0xee7948
    case Yanaginezu         // 和色名 柳鼠 / 0xc8d5bb
    case Tomekon            // 和色名 留紺 / 0x1c305c
    case Hakuji             // 和色名 白磁 / 0xf8fbf8
    case Shiracha           // 和色名 白茶 / 0xddbb99
    case KakiIro            // 和色名 柿色 / 0xed6d3d
    case Urahayanagi        // 和色名 裏葉柳 / 0xc1d8ac
    case Koiai              // 和色名 濃藍 / 0x0f2350
    case KinariIro          // 和色名 生成り色 / 0xfbfaf5
    case Akashirotsurubami  // 和色名 赤白橡 / 0xd7a98c
    case Kiaka              // 和色名 黄赤 / 0xec6800
    case WasabiIro          // 和色名 山葵色 / 0xa8bf93
    case Tetsukon           // 和色名 鉄紺 / 0x17184b
    case NyuuhakuShoku      // 和色名 乳白色 / 0xf3f3f3
    case Araigaki           // 和色名 洗柿 / 0xf2c9ac
    case NinjinIro          // 和色名 人参色 / 0xec6800
    case OitakeIro          // 和色名 老竹色 / 0x769164
    case Shikkoku           // 和色名 漆黒 / 0x0d0015
    case Shironeri          // 和色名 白練 / 0xf3f3f2
    case TorinokoIro        // 和色名 鳥の子色 / 0xfff1cf
    case DaidaiIro          // 和色名 橙色 / 0xee7800
    case Byakuroku          // 和色名 白緑 / 0xd6e9ca
    case AwafujiIro         // 和色名 淡藤色 / 0xbbc8e6
    case SoShoku            // 和色名 素色 / 0xeae5e3
    case HachimitsuIro      // 和色名 蜂蜜色 / 0xfddea5
    case Terigaki           // 和色名 照柿 / 0xeb6238
    case Usumoegi           // 和色名 淡萌黄 / 0x93ca76
    case FujiIro            // 和色名 藤色 / 0xbbbcde
    case Shiraumenezu       // 和色名 白梅鼠 / 0xe5e4e6
    case HadaIro            // 和色名 肌色 / 0xfce2c4
    case Akadaidai          // 和色名 赤橙 / 0xea5506
    case Yanagizome         // 和色名 柳染 / 0x93b881
    case BenikakesoraIro    // 和色名 紅掛空色 / 0x8491c3
    case Shironezu          // 和色名 白鼠 / 0xdcdddd
    case UsutamagoIro       // 和色名 薄卵色 / 0xfde8d0
    case Kinaka             // 和色名 金赤 / 0xea5506
    case Usumoegi2          // 和色名 薄萌葱 / 0xbadcad
    case Benimidori         // 和色名 紅碧 / 0x8491c3
    case Kinunezu           // 和色名 絹鼠 / 0xdddcd6
    case Yuuou              // 和色名 雄黄 / 0xf9c89b
    case ShuIro             // 和色名 朱色 / 0xeb6101
    case Fukagawanezumi     // 和色名 深川鼠 / 0x97a791
    case Konkikyou          // 和色名 紺桔梗 / 0x4d5aaf
    case Haiao              // 和色名 灰青 / 0xc0c6c9
    case Sharegaki          // 和色名 洒落柿 / 0xf7bd8f
    case KomugiIro          // 和色名 小麦色 / 0xe49e61
    case Wakamidori         // 和色名 若緑 / 0x98d98e
    case HanaIro            // 和色名 花色 / 0x4d5aaf
    case Ginnezu            // 和色名 銀鼠 / 0xafafb0
    case Akakou             // 和色名 赤香 / 0xf6b894
    case NiIro              // 和色名 丹色 / 0xe45e32
    case Asamidori          // 和色名 浅緑 / 0x88cb7f
    case Konai              // 和色名 紺藍 / 0x4a488e
    case Usunibi            // 和色名 薄鈍 / 0xadadad
    case TonokoIro          // 和色名 砥粉色 / 0xf4dda5
    case Kicha              // 和色名 黄茶 / 0xe17b34
    case Usumidori          // 和色名 薄緑 / 0x69b076
    case Benikikyou         // 和色名 紅桔梗 / 0x4d4398
    case UsuzumiIro         // 和色名 薄墨色 / 0xa3a3a2
    case NikuIro            // 和色名 肉色 / 0xf1bf99
    case NikkeiIro          // 和色名 肉桂色 / 0xdd7a56
    case Aonibi             // 和色名 青鈍 / 0x6b7b6e
    case KikyouIro          // 和色名 桔梗色 / 0x5654a2
    case SuzuIro            // 和色名 錫色 / 0x9ea1a3
    case HitoIro            // 和色名 人色 / 0xf1bf99
    case AkakuchibaIro      // 和色名 赤朽葉色 / 0xdb8449
    case Seijinezu          // 和色名 青磁鼠 / 0xbed2c3
    case Fujinando          // 和色名 藤納戸 / 0x706caa
    case Sunezumi           // 和色名 素鼠 / 0x9fa0a0
    case TyoujiIro          // 和色名 丁子色 / 0xefcd9a
    case Kourozen           // 和色名 黄櫨染 / 0xd66a35
    case Usuao              // 和色名 薄青 / 0x93b69c
    case BenikakehanaIro    // 和色名 紅掛花色 / 0x68699b
    case NezumiIro          // 和色名 鼠色 / 0x949495
    case KouIro             // 和色名 香色 / 0xefcd9a
    case TanpopoIro         // 和色名 蒲公英色 / 0xffd900
    case Sabiseiji          // 和色名 錆青磁 / 0xa6c8b2
    case ShionIro           // 和色名 紫苑色 / 0x867ba9
    case Genjinezu          // 和色名 源氏鼠 / 0x888084
    case Usukou             // 和色名 薄香 / 0xf0cfa0
    case KiIro              // 和色名 黄色 / 0xffd900
    case RokushouIro        // 和色名 緑青色 / 0x47885e
    case ShirafujiIro       // 和色名 白藤色 / 0xdbd0e6
    case HaiIro             // 和色名 灰色 / 0x7d7d7d
    case Usuki              // 和色名 浅黄 / 0xedd3a1
    case Tyuuki             // 和色名 中黄 / 0xffea00
    case Chitosemidori      // 和色名 千歳緑 / 0x316745
    case Fujimurasaki       // 和色名 藤紫 / 0xa59aca
    case NamariIro          // 和色名 鉛色 / 0x7b7c7d
    case KareIro            // 和色名 枯色 / 0xe0c38c
    case NanohanaIro        // 和色名 菜の花色 / 0xffec47
    case WakatakeIro        // 和色名 若竹色 / 0x68be8d
    case SumireIro          // 和色名 菫色 / 0x7058a3
    case NibiIro            // 和色名 鈍色 / 0x727171
    case Usukou2            // 和色名 淡香 / 0xf3bf88
    case KihadaIro          // 和色名 黄檗色 / 0xfef263
    case Midori             // 和色名 緑 / 0x3eb370
    case Aomurasaki         // 和色名 青紫 / 0x674598
    case Sumi               // 和色名 墨 / 0x595857
    case AnzuIro            // 和色名 杏色 / 0xf7b977
    case TamagoIro          // 和色名 卵色 / 0xfcd575
    case TokiwaIro          // 和色名 常磐色 / 0x007b43
    case ShoubuIro          // 和色名 菖蒲色 / 0x674196
    case Dobunezumi         // 和色名 丼鼠 / 0x595455
    case ShinonomeIro       // 和色名 東雲色 / 0xf19072
    case HanabaIro          // 和色名 花葉色 / 0xfbd26b
    case Chigusanezu        // 和色名 千草鼠 / 0xbed3ca
    case RindouIro          // 和色名 竜胆色 / 0x9079ad
    case KeshizumiIro       // 和色名 消炭色 / 0x524e4d
    case AkebonoIro         // 和色名 曙色 / 0xf19072
    case KariyasuIro        // 和色名 刈安色 / 0xf5e56b
    case ChigusaIro         // 和色名 千草色 / 0x92b5a9
    case Edomurasaki        // 和色名 江戸紫 / 0x745399
    case Aisumicha          // 和色名 藍墨茶 / 0x474a4d
    case SangoshuIro        // 和色名 珊瑚朱色 / 0xee836f
    case ToumorokoshiIro    // 和色名 玉蜀黍色 / 0xeec362
    case SeijiIro           // 和色名 青磁色 / 0x7ebea5
    case Honmurasaki        // 和色名 本紫 / 0x65318e
    case YoukanIro          // 和色名 羊羹色 / 0x383c3c
    case Kokikuchinashi     // 和色名 深支子 / 0xeb9b6f
    case KanariaIro         // 和色名 金糸雀色 / 0xebd842
    case AotakeIro          // 和色名 青竹色 / 0x7ebeab
    case BudouIro           // 和色名 葡萄色 / 0x522f60
    case RouIro             // 和色名 蝋色 / 0x2b2b2b
    case Sohi               // 和色名 纁 / 0xe0815e
    case KikuchinashiIro    // 和色名 黄支子色 / 0xffdb4f
    case Tokiwamidori       // 和色名 常磐緑 / 0x028760
    case Fukamurasaki       // 和色名 深紫 / 0x493759
    case Kuro               // 和色名 黒 / 0x2b2b2b
    case Usukihi            // 和色名 浅緋 / 0xdf7163
    case KuchinashiIro      // 和色名 支子色 / 0xfbca4d
    case TokusaIro          // 和色名 木賊色 / 0x3b7960
    case Shikoku            // 和色名 紫黒 / 0x2e2930
    case KarasubaIro        // 和色名 烏羽色 / 0x180614
    case Masoho             // 和色名 真赭 / 0xd57c6b
    case HimawariIro        // 和色名 向日葵色 / 0xfcc800
    case Biroudo            // 和色名 天鵞絨 / 0x2f5d50
    case Murasaki           // 和色名 紫 / 0x884898
    case Tetsuguro          // 和色名 鉄黒 / 0x281a14
    case Araishu            // 和色名 洗朱 / 0xd0826c
    case YamabukiIro        // 和色名 山吹色 / 0xf8b500
    case Mushiao            // 和色名 虫襖 / 0x3a5b52
    case Usubudou           // 和色名 薄葡萄 / 0xc0a2c7
    case NurebaIro          // 和色名 濡羽色 / 0x000b00
    case Enshuucha          // 和色名 遠州茶 / 0xca8269
    case UkonIro            // 和色名 鬱金色 / 0xfabf14
    case KawaIro            // 和色名 革色 / 0x475950
    case Shikon             // 和色名 紫紺 / 0x460e44
    case Kokutan            // 和色名 黒壇 / 0x250d00
    case BenikabaIro        // 和色名 紅樺色 / 0xbb5548
    case Touou              // 和色名 藤黄 / 0xf7c114
    case Fukamidori         // 和色名 深緑 / 0x00552e
    case AnkouShoku         // 和色名 暗紅色 / 0x74325c
    case Kenpoukurocha      // 和色名 憲法黒茶 / 0x241a08
    case Soho               // 和色名 赭 / 0xab6953
    case Konjiki            // 和色名 金色 / 0xe6b422
    case TetsuIro           // 和色名 鉄色 / 0x005243
    case KuwanomiIro        // 和色名 桑の実色 / 0x55295b
    case AnkokuShoku        // 和色名 暗黒色 / 0x16160e
}

extension JpnColor: HKLColorTableRepresentable {
    public func name() -> String {
        return jpnColors[self.rawValue].name
    }

    public func uiColor() -> UIColor {
        return UIColor(hexValue: jpnColors[self.rawValue].hex)
    }

    public func count() -> Int {
        return jpnColors.count
    }
}

